name: flutter_image_picker_example
description: Flutter Image Picker Example App
homepage: https://github.com/Iconica-Development/flutter_image_picker

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_image_picker:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_iconica_analysis:
    hosted: https://forgejo.internal.iconica.nl/api/packages/internal/pub
    version: ^7.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/placeholder.png
