name: flutter_image_picker
description: A Flutter Image Picking package.
version: 1.0.3
repository: https://github.com/Iconica-Development/flutter_image_picker

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.8.5+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mocktail: ^0.3.0

flutter:
